name: GhostKits
version: '${project.version}'
main: me.ghostdevelopment.ghostkits.GhostKit
author: GhostAndry
softdepend:
  - PlaceholderAPI

commands:
  ghostkits:
    aliases:
      - gkits
      - gkit
      - kits
      - kit

permissions:
  ghostkits.*:
    default: op